project:
  type: website

website:
  title: "Matthew A. Turner, PhD"
  navbar:
    left:
        - text: "SubtleTea Solutions"
          href: SubtleTeaSolutions.qmd
    right:
        - text: Email
          href: "mailto:matt@mat.phd"
        - text: LinkedIn
          href: "https://www.linkedin.com/in/mt-digital/"
        - text: GitHub
          href: "https://github.com/mt-digital"
         
    collapse: true
    pinned: true
    search: true
format:
  html:
    theme: styles.scss
    toc: true



